name: apiverve_invoicegenerator
description: Invoice Generator is a simple tool for generating invoices. It returns a PDF of the generated invoice.
version: 1.1.14
homepage: https://apiverve.com/marketplace/invoicegenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/invoicegenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
